# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-01-26 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0003_auto_20200126_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadworksplatform',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='broadworksplatform',
            name='ip',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
