# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2020-03-07 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0020_auto_20200304_0114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicetype',
            options={},
        ),
    ]
